#!/bin/bash -ex

[ $WORKSPACE ] && export GOPATH=$WORKSPACE
export PATH="$GOPATH/bin:$PATH"

go get github.com/tools/godep
go get github.com/onsi/ginkgo/ginkgo
cd $GOPATH/src/hub.jazz.net/git/bluemixgarage/lrsc-bridge
godep restore
ginkgo -r
