#!/bin/bash

main() {
  . script/run_with_env
  copy_lrsc_cert_and_key_from_credential_store
  "${BASE_PATH}/script/test"
  "${BASE_PATH}/script/build"
  "${BASE_PATH}/script/deploy"
}

copy_lrsc_cert_and_key_from_credential_store() {
  BASE_PATH="${BASE_PATH:?must be defined}"
  CREDENTIALS_STORE_CLIENT_CERT="${CREDENTIALS_STORE_CLIENT_CERT:?must be defined}"
  CREDENTIALS_STORE_CLIENT_KEY="${CREDENTIALS_STORE_CLIENT_KEY:?must be defined}"
  LRSC_CLIENT_CERT="${LRSC_CLIENT_CERT:?must be defined}"
  LRSC_CLIENT_KEY="${LRSC_CLIENT_KEY:?must be defined}"

  pushd "$BASE_PATH" >/dev/null
    cp "$CREDENTIALS_STORE_CLIENT_CERT" "$LRSC_CLIENT_CERT"
    cp "$CREDENTIALS_STORE_CLIENT_KEY" "$LRSC_CLIENT_KEY"
  popd >/dev/null
}

main
