#!/bin/bash -e

APP_PKG_NAME="hub.jazz.net/git/bluemixgarage/lrsc-bridge"
ARGS="$@"

main() {
  . script/run_with_env
  install_test_dependencies
  within_app use_vendored_packages
  within_app run_tests
}

install_test_dependencies() {
  which godep 2>&1 > /dev/null || go get github.com/tools/godep
  which ginkgo 2>&1 > /dev/null || go get github.com/onsi/ginkgo/ginkgo
}

within_app() {
  pushd "${GOPATH}/src/${APP_PKG_NAME}" >/dev/null
  "$@"
  popd >/dev/null
}

use_vendored_packages() {
  godep restore
}

run_tests() {
  ginkgo $ARGS -r -randomizeAllSpecs
}

main
