#!/bin/bash

APP_PKG_NAME="hub.jazz.net/git/bluemixgarage/lrsc-bridge"
ARGS="$@"

main() {
  . scripts/run_with_env
  within_app use_vendored_packages
  within_app build
}

within_app() {
  pushd "${GOPATH}/src/${APP_PKG_NAME}"
    "$@"
  popd
}

use_vendored_packages() {
  godep restore
}

build() {
  APP_BINARY="${APP_BINARY:?must be defined}"
  ARGS="${ARGS:?must be defined}"

  go build -o "$APP_BINARY" $ARGS
}

main
