#!/bin/bash -e

APP_PKG_NAME="hub.jazz.net/git/bluemixgarage/lrsc-bridge"
ARGS="$@"

main() {
	. scripts/run_with_env
	within_app use_vendored_packages
	within_app build
}

within_app() {
	pushd "${GOPATH}/src/${APP_PKG_NAME}" 1>&-
		"$@"
	popd 1>&-
}

use_vendored_packages() {
	godep restore
}

build() {
	go build $ARGS
}

main
