#!/bin/bash -e

main() {
  . scripts/run_with_env
  login_to_bluemix
  deploy_to_bluemix
}

login_to_bluemix() {
  CF_URL="${CF_URL:?must be defined}"
  CF_USERNAME="${CF_USERNAME:?must be defined}"
  CF_PASSWORD="${CF_PASSWORD:?must be defined}"
  CF_ORG="${CF_ORG:?must be defined}"
  CF_SPACE="${CF_SPACE:?must be defined}"

  cf apps || cf login -a "$CF_URL" -u "$CF_USERNAME" -p "$CF_PASSWORD" -o "$CF_ORG" -s "$CF_SPACE"
}

deploy_to_bluemix() {
  CF_MANIFEST="${CF_MANIFEST:?must be defined}"

  cf push -f "$CF_MANIFEST"
}

main
