#!/bin/bash

main() {
  . scripts/run_with_env
  build_for_bluemix
  login_to_bluemix
  deploy_to_bluemix
}

login_to_bluemix() {
  CF_URL="${CF_URL:?must be defined}"
  CF_USERNAME="${CF_USERNAME:?must be defined}"
  CF_PASSWORD="${CF_PASSWORD:?must be defined}"
  CF_ORG="${CF_ORG:?must be defined}"
  CF_SPACE="${CF_SPACE:?must be defined}"

  if ! cf apps | grep -e "org ${CF_ORG}.*space ${CF_SPACE}.*as ${CF_USERNAME}" >/dev/null
  then
    cf login -a "$CF_URL" -u "$CF_USERNAME" -p "$CF_PASSWORD" -o "$CF_ORG" -s "$CF_SPACE"
  fi
}

build_for_bluemix() {
  BASE_PATH="${BASE_PATH:?must be defined}"
  export GOOS="${CF_GOOS:?must be defined}"
  export GOARCH="${CF_GOARCH:?must be defined}"

  "${BASE_PATH}/scripts/build"
}

deploy_to_bluemix() {
  CF_MANIFEST="${CF_MANIFEST:?must be defined}"

  cf push -f "$CF_MANIFEST"
}

main
